"""Add master key to sekolah

Revision ID: ff366ad23bce
Revises: 005_add_sindas_sync_log
Create Date: 2026-08-21 07:53:00.497046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff366ad23bce'
down_revision: Union[str, None] = '005_add_sindas_sync_log'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sekolah', sa.Column('public_key_pem', sa.Text(), nullable=True, comment='Public Key RSA Master Key sekolah (PEM)'))
    op.add_column('sekolah', sa.Column('mk_version', sa.Integer(), server_default='0', nullable=False, comment='Versi Master Key yang aktif. 0 = belum di-setup'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sekolah', 'mk_version')
    op.drop_column('sekolah', 'public_key_pem')
    # ### end Alembic commands ###
